### ISSUE TITLE
Express Routes

### ISSUE THREAD

**Issue by MarkKelly00** [MarkKelly00/codeLocker#8]
**CodeBlock routes**
- "/api/codeblock" 
> - put (replaces codeBlock)
> - post (add new codeblock)

- "/api/codeblock/author/:id"
> - get (get all user code)
> - delete (delete all user codeblocks)

- "/api/codeblock/:id"
> - delete (delete codeblock by id)
> - get (get codeblock by id)

**User routes**
- "/api/users/"
> -  post (create new user)

- "/api/users/:id"
> - get (get user by id)

**Comment by Beki-G** [comment]
updated the "/api/codeblock/:id" - delete Method #42
